### PR TITLE
Refactor to Next.js

### PR DESCRIPTION
**Pull request by advaiyalad**
This PR refactors this website to use a framework called [Next.js](https://next.js.org).
This will allow for further dynamic functionality in the future (as in the next week), including users, an admin dashboard, a working shopping cart, and more.

A lot of the deleted files are really refactored into other places, but Git can't show that, sadly.

Note: for future backend functionality, so far the plan is to use TRPC and make this by hand, but [Medusa](https://docs.medusajs.com) is another option.

### CODE REVIEW

**Comment by Blue-Robin-Taken** [comment]
Bro you should definitely join the discord

**Comment by RedCat888** [comment]
how has this guy not been on it

**Review by Blue-Robin-Taken — APPROVED** [review]
Very nice changes

**Review by RedCat888 — APPROVED** [review]
Looks great, we could work on organization and naming a bit. But overall the code is amazing

**Pull request merged**
