### PR TITLE
Add development setup to README

### PR DESCRIPTION
**Pull request by advaiyalad**
Explains the setup of Node.js and pnpm, along with how to start the development server. Fixes formatting with classnames in README as well.

### CODE REVIEW

**Review by Blue-Robin-Taken — CHANGES_REQUESTED** [review]
The setup is different for something like codespaces or any other IDE. Therefore, I believe that it is best we do not include this section in the readme. Instead, we can have a list of dependencies.

**Comment by advaiyalad** [comment]
How about we rename it to local development because it still applies to anyone doing local development?

**Comment by Blue-Robin-Taken** [comment]
That'd work @advaiyalad

**Review by Blue-Robin-Taken — APPROVED** [review]

**Review by RedCat888 — APPROVED** [review]
pretty simple

looks good

**Pull request merged**
