### PR TITLE
Added automatic topnav

### PR DESCRIPTION
**Pull request by Blue-Robin-2**
# What changed
Made it easier to edit the topnav and make it the same across all files.

# How it does this
It uses a js file to append the topnav HTML to a div with a function. If the topnav HTML file is edited, it will be shown across all files. This makes it a lot easier to keep consistency.

### CODE REVIEW

**Review by LizzyEll — COMMENTED** [review]
I don't think I really like this idea too much, could you give me an explanation to what you are trying to accomplish with this?

**Comment by Blue-Robin-2** [comment]
I'm trying to make the topnav the same for all pages and make it easily editable. If we add more pages, it should be really easy to implement. If we decide on a redesign, it'll save a lot of time.

**Review by LizzyEll — APPROVED** [review]
I like the idea, I think we should implement maybe a template system for our pages as in, when someone clicks a webpage, its the same page, just different scripted date inputed into it. Kinda like Python's Flask or Node JS ExpressJS

**Comment by Blue-Robin-2** [comment]
We could use Jinja. I've used it before. Super useful for something like this.

**Comment by RedCat888** [comment]
Elaborate on what it is and why we should use it (too lazy to Google it up lmao)

**Comment by RedCat888** [comment]
Also having it separately was a great idea, increases efficiency and consistency

**Comment by LizzyEll** [comment]
Isn't jinja for python pages? Github Pages only supports static html

**Pull request merged**
