### PR TITLE
Style and optimization

### LINKED ISSUE #80: Better Web Design
# General web design things we need
This issue is for general web design things. Any pull requests should be linked to this issue so that we can have a framework for our web design.

## Make a better color scheme
Currently the website could look a bit better as it's currently just green and stuff (which is quite goofy)

## Make some web animations for transitions
The website currently doesn't have any transitions and would be greatly improved by some transitions (other than the one that we have for \<h1> tags)

## Accessibility 
It's important that our website is accessible to everyone (on all devices as well)

### PR DESCRIPTION
**Pull request by LizzyEll**
# Pull Request

## Commit One
* FIxed Awkware title size

## Commit Two
* Changed the `img` objects to Next.JS `Image` objects
The site's main page was taking up to 30 seconds to compile on a codespace and as soon as I interchanged those, it got a lot faster. 

## Commit Three
* Fix a weird folder name that would've caused issues moving on

### CODE REVIEW

**Comment by Blue-Robin-Taken** [comment]
I have a *ton* of homework recently and I'll get back to this on the weekend

**Comment by Blue-Robin-Taken** [comment]
Also please make this for `dev` and not into `main`

**Comment by Blue-Robin-Taken** [comment]
I realized that I don't need to close it for you to change branches

**Review by Blue-Robin-Taken — CHANGES_REQUESTED** [review]
Change branch from `main` to `dev`

**Comment by LizzyEll** [comment]
@Blue-Robin-Taken @RedCat888 
Look throught the PR

**Comment by RedCat888** [comment]
Please maintain a branch within the repo, instead of merging a fork. However I will eventually approve this after we get the preview link this one time. Your changes/code all look good however.

**Review by Blue-Robin-Taken — COMMENTED** [review]
So far this looks pretty awesome, but I gotta see the preview to make sure it works (I'm going to try to deploy it)

**Pull request merged**
